#theme: jekyll-theme-architect
lang: en-UK
title: Fliss Power Counselling
description: Person-Centred & Experiential Counsellor and Psychotherapist in Sheffield
keywords: Counsellor, Psychotherapist, Sheffield, Person-centred

include: ["_pages"]
baseurl: /flisspowercounselling/

plugins:
  - jekyll-seo-tag
