#theme: jekyll-theme-architect
lang: en-UK
title: Fliss Power Counselling
description: Person-Centred & Experiential Counsellor and Psychotherapist in Sheffield
keywords: Fliss, Power, Counsellor, Psychotherapist, Therapist, Sheffield, S11, Person-Centred, Person-Centered, UKCP, depression, anxiety

include: ["_pages"]
baseurl: /
url: http://www.flisspowercounselling.co.uk

plugins:
  - jekyll-seo-tag
